# Generated by Django 4.2.3 on 2023-08-09 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_contacts_phone_number_alter_product_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='changed_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
    ]
