# Generated by Django 4.2.3 on 2023-08-09 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_changed_at_alter_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='псевдоним')),
                ('body', models.TextField(verbose_name='текст блога')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='превью')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='запись опубликована?')),
                ('views', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('created_at',),
            },
        ),
    ]
