# Generated by Django 4.2.3 on 2023-08-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.CharField(default=False, verbose_name='товар опубликован на сайте?'),
        ),
    ]
